'use client';
import {useState,useEffect,useMemo,useCallback,useRef} from 'react';
import dynamic from 'next/dynamic';
import PhoneLogin from './PhoneLogin';
import {MapPin,Search,Plus,ArrowUpLeft,SlidersHorizontal,Camera,Tent,Drill,Bike,Home,Monitor,Package,ShieldCheck,MessageCircle,X,LocateFixed,Star,LogOut,CalendarDays,Grid2X2,Map as MapIcon,PartyPopper,House,Compass,ClipboardList,UserRound,Phone,Utensils,MoreHorizontal} from 'lucide-react';
import type {User} from '@supabase/supabase-js';
import {db} from '@/lib/supabase';
import {demo} from '@/lib/demo';
import {categories,statuses,type Item,type Booking,type Review,type Message,type Point} from '@/lib/types';
import {distanceKm,normalizePhone} from '@/lib/domain.mjs';
import {regions} from '@/lib/regions';
const Map=dynamic(()=>import('./Map'),{ssr:false,loading:()=> <div className="map loading">جارٍ تحميل الخريطة…</div>});
const icons=[Package,Camera,Tent,Drill,Bike,Home,Monitor,PartyPopper,Utensils,MoreHorizontal];
function Art({item}:{item:Item}){const Icon=icons[categories.indexOf(item.category)]||Package;return item.images[0]?<img className="item-image" src={item.images[0]} alt={item.title}/>:<div className={'item-art art-'+categories.indexOf(item.category)}><Icon size={76} strokeWidth={1.2}/><span>{item.category}</span></div>}
function Modal({title,close,children,notice}:{title:string;close:()=>void;children:React.ReactNode;notice?:string}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);
 return <dialog ref={ref} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="إغلاق"><X/></button></div>{notice&&<p className="dialog-notice" role="alert">{notice}</p>}{children}</dialog>
}
async function cleanImage(file:File):Promise<Blob>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('اختر صور JPG أو PNG أو WebP بحجم أقل من 5 ميجابايت');
 const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('تعذرت معالجة الصورة')),'image/webp',.85));
}
export default function Marketplace({initialItemId}:{initialItemId?:string}){
 const [items,setItems]=useState<Item[]>(db?[]:demo),[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(!!db),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [view,setView]=useState<'explore'|'dashboard'>('explore'),[modal,setModal]=useState<'auth'|'add'|null>(null),[selected,setSelected]=useState<Item|null>(null);
 const [query,setQuery]=useState(''),[category,setCategory]=useState('الكل'),[radius,setRadius]=useState(20),[maxPrice,setMaxPrice]=useState(1000),[minPrice,setMinPrice]=useState(0),[filters,setFilters]=useState(false),[mode,setMode]=useState<'both'|'list'|'map'>('both');
 const [center,setCenter]=useState<Point>({lat:24.78,lng:46.63}),[locationLabel,setLocationLabel]=useState('موقعي'),[manual,setManual]=useState(false),[pickRegion,setPickRegion]=useState<string|null>(null);
 const [bookings,setBookings]=useState<Booking[]>([]),[reviews,setReviews]=useState<Review[]>([]),[chat,setChat]=useState<Booking|null>(null),[messages,setMessages]=useState<Message[]>([]),[dashboardTab,setDashboardTab]=useState<'rentals'|'incoming'|'items'>('rentals');
 const [realDistanceKm,setRealDistanceKm]=useState<number|null>(null),[reviewBooking,setReviewBooking]=useState<Booking|null>(null),[addPoint,setAddPoint]=useState<Point|null>(null);
 const refresh=useCallback(async()=>{if(!db)return;setLoading(true);const [a,b]=await Promise.all([db.from('items').select('*').order('created_at',{ascending:false}),db.from('reviews').select('*')]);if(a.error)setNotice('تعذر تحميل الأغراض. تحقق من إعداد قاعدة البيانات والاتصال.');else setItems(a.data||[]);if(!b.error)setReviews(b.data||[]);setLoading(false)},[]);
 const refreshBookings=useCallback(async()=>{if(!db||!user){setBookings([]);return}const {data,error}=await db.from('bookings').select('*').order('created_at',{ascending:false});if(error)setNotice('تعذر تحميل الحجوزات');else setBookings(data||[])},[user]);
 useEffect(()=>{refresh();if(!db)return;db.auth.getUser().then(({data})=>setUser(data.user));const {data}=db.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);setRealDistanceKm(null);setChat(null)});return()=>data.subscription.unsubscribe()},[refresh]);
 useEffect(()=>{refreshBookings()},[refreshBookings]);
 useEffect(()=>{if(!chat||!db)return;let cancelled=false;const load=async()=>{const {data,error}=await db!.from('messages').select('*').eq('booking_id',chat.id).order('created_at');if(!cancelled){if(error)setNotice('تعذر تحميل المحادثة');else setMessages(data||[])}};setMessages([]);load();const timer=setInterval(load,4000);return()=>{cancelled=true;clearInterval(timer)}},[chat]);
 useEffect(()=>{setRealDistanceKm(null);if(!db||!user||!selected)return;let active=true;db.rpc('get_pickup_distance',{p_item:selected.id,p_lat:center.lat,p_lng:center.lng}).then(({data,error})=>{if(active&&!error)setRealDistanceKm(data)});return()=>{active=false}},[selected,user,bookings,center]);
 const visible=useMemo(()=>items.filter(i=>(category==='الكل'||i.category===category)&&(i.title+' '+i.description+' '+i.area).includes(query)&&i.daily_price>=minPrice&&i.daily_price<=maxPrice&&distanceKm(center,i)<=radius),[items,category,query,minPrice,maxPrice,center,radius]);
 const initialOpened=useRef(false);
 useEffect(()=>{if(initialOpened.current||!initialItemId||loading)return;initialOpened.current=true;const found=items.find(i=>i.id===initialItemId);if(found)setSelected(found);else setNotice('الغرض غير موجود أو تعذر تحميله')},[initialItemId,items,loading]);
 useEffect(()=>{const back=()=>{const id=window.location.pathname.split('/items/')[1];setSelected(items.find(i=>i.id===id)||null)};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back)},[items]);
 const choose=useCallback((item:Item)=>{setNotice('');setSelected(item);window.history.pushState(null,'',`/items/${item.id}`)},[]);
 const closeDetails=()=>{setSelected(null);window.history.pushState(null,'','/')};
 const requireUser=()=>{if(!db){setNotice('هذه معاينة ببيانات توضيحية. فعّل Supabase وفق دليل التشغيل لاستخدام الحسابات والحجوزات.');return false}if(!user){setModal('auth');return false}return true};
 const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);try{await action()}catch(e){setNotice(e instanceof Error?e.message:'تعذر تنفيذ العملية. حاول مجددًا.')}finally{setBusy(false)}};
 const locate=(forItem=false)=>{if(!navigator.geolocation){setNotice(forItem?'المتصفح لا يدعم تحديد الموقع. أدخل الإحداثيات يدويًا.':'المتصفح لا يدعم تحديد الموقع. اختر منطقتك ومدينتك من القائمة.');return}navigator.geolocation.getCurrentPosition(p=>{const point={lat:p.coords.latitude,lng:p.coords.longitude};if(forItem)setAddPoint(point);else {setCenter(point);setLocationLabel('بالقرب من موقعي')}},()=>{setNotice(forItem?'تعذر تحديد الموقع. اسمح بإذن الموقع أو أدخل الإحداثيات يدويًا.':'تعذر تحديد الموقع. اسمح بإذن الموقع أو اختر منطقتك ومدينتك من القائمة.');if(!forItem)setManual(true)},{enableHighAccuracy:true,timeout:15000})};
 const change=(b:Booking,status:string)=>run(async()=>{const {error}=await db!.rpc('change_booking',{p_booking:b.id,p_status:status});if(error)throw Error(error.message);await refreshBookings();setNotice('تم تحديث حالة الحجز')});
 const itemOf=(b:Booking)=>items.find(i=>i.id===b.item_id);
 const itemTitle=(b:Booking)=>itemOf(b)?.title||'غرض';
 const average=(id:string)=>{const rs=reviews.filter(r=>r.item_id===id);return rs.length?(rs.reduce((a,r)=>a+r.rating,0)/rs.length).toFixed(1):null};
 return <><header className="header"><a className="brand" href="/" aria-label="قريب الرئيسية"><span className="brand-symbol"><MapPin size={25}/></span>قريب<span className="brand-dot">.</span></a><nav><button className={view==='explore'?'nav-active':''} onClick={()=>setView('explore')}>استكشف</button><button className={view==='dashboard'?'nav-active':''} onClick={()=>{if(requireUser())setView('dashboard')}}>أغراضي وحجوزاتي</button></nav><div className="header-actions"><button className="primary compact" onClick={()=>{if(requireUser()){setAddPoint(null);setModal('add')}}}><Plus size={18}/> أضف غرضك</button>{user?<button className="icon-button" aria-label="تسجيل الخروج" onClick={()=>run(async()=>{const {error}=await db!.auth.signOut();if(error)throw error;setView('explore');setBookings([]);setSelected(null)})}><LogOut size={20}/></button>:<button className="login" onClick={()=>setModal('auth')}>دخول</button>}</div></header>
 {!db&&<div className="demo-note">معاينة توضيحية · تُفعّل الحسابات والحجوزات عند ربط Supabase</div>}
 {notice&&<div className="notice" role="status"><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="إغلاق التنبيه"><X size={18}/></button></div>}
 <main>{view==='explore'?<><section className="intro"><div><div className="eyebrow">أشياء تحتاجها، وأشخاص قريبون منك</div><h1>دام تقدر تستأجره، <span>ليش تشتريه؟</span></h1><p>اكتشف أغراضًا مفيدة في حيك، واستأجرها للمدة التي تحتاجها.</p></div><button className="location" onClick={()=>setManual(!manual)}><span className="brand-symbol tiny"><MapPin size={13}/></span>{locationLabel}<span>أماكن أخرى</span></button></section>
 {manual&&<div className="manual-location panel"><label>المنطقة<select value={pickRegion??''} onChange={e=>setPickRegion(e.target.value||null)}><option value="">اختر المنطقة</option>{Object.keys(regions).map(r=><option key={r} value={r}>{r}</option>)}</select></label>{pickRegion&&<label>المدينة أو المحافظة<select defaultValue="" onChange={e=>{const c=regions[pickRegion][e.target.value];if(!c)return;setCenter({lat:c[0],lng:c[1]});setLocationLabel(e.target.value);setManual(false);setPickRegion(null)}}><option value="" disabled>اختر المدينة</option>{Object.keys(regions[pickRegion]).map(c=><option key={c} value={c}>{c}</option>)}</select></label>}<button type="button" className="secondary" onClick={()=>locate()}><LocateFixed size={18}/> استخدام موقعي الحالي</button></div>}
 <div className="search-row"><div className="search"><Search size={22}/><input aria-label="البحث عن غرض" placeholder="وش تحتاج اليوم؟ كاميرا، خيمة، أدوات…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="مسح البحث"><X size={18}/></button>}</div><button className={'secondary '+(filters?'selected':'')} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={18}/> الفلاتر</button><button className="location-button" onClick={()=>locate()} aria-label="استخدام موقعي الحالي"><LocateFixed size={21}/></button></div>
 {filters&&<div className="filter-panel panel"><label>المسافة: {radius} كم<input type="range" min="1" max="100" value={radius} onChange={e=>setRadius(Number(e.target.value))}/></label><label>أقل سعر يومي<input type="number" min="0" max={maxPrice} value={minPrice} onChange={e=>setMinPrice(Number(e.target.value))}/></label><label>أعلى سعر يومي<input type="number" min={minPrice} max="100000" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label><button className="text-button" onClick={()=>{setRadius(20);setMinPrice(0);setMaxPrice(1000);setCategory('الكل');setQuery('')}}>إعادة ضبط</button></div>}
 <div className="categories">{categories.map((c,index)=>{const Icon=icons[index];return <button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}><Icon size={21}/>{c}</button>})}</div>
 <div className="results-head"><div><h2>اكتشف ما حولك</h2><span>{loading?'جارٍ التحميل…':`${visible.length} أغراض ضمن ${radius} كم · المسافات تقريبية`}</span></div><div className="view-toggle"><button aria-label="عرض قائمة" className={mode==='list'?'active':''} onClick={()=>setMode('list')}><Grid2X2 size={18}/></button><button className={mode==='both'?'active desktop-only':'desktop-only'} onClick={()=>setMode('both')}>قائمة وخريطة</button><button aria-label="عرض خريطة" className={mode==='map'?'active':''} onClick={()=>setMode('map')}><MapIcon size={18}/></button></div></div>
 <div className={'results mode-'+mode}>{mode!=='map'&&<div className="cards">{visible.map(item=><button key={item.id} className="item-card" onClick={()=>choose(item)}><div className="image-wrap"><Art item={item}/><span className="category-tag">{item.category}</span></div><div className="card-body"><div className="card-meta"><span><MapPin size={14}/>{distanceKm(center,item).toFixed(1)} كم تقريبًا</span><span className="rating"><Star size={14}/>{average(item.id)||'جديد'}</span></div><h3>{item.title}</h3><p>{item.area}</p><div className="card-bottom"><span><strong>{item.daily_price}</strong> ر.س <small>/ يوم</small></span><ArrowUpLeft size={21}/></div></div></button>)}{!loading&&!visible.length&&<div className="empty"><Package size={42}/><h3>لا توجد أغراض مطابقة</h3><p>وسّع المسافة أو غيّر الفلاتر، أو أضف أول غرض في منطقتك.</p></div>}</div>}{mode!=='list'&&<aside className="map-panel"><Map items={visible} center={center} onSelect={choose}/><div className="map-caption"><ShieldCheck size={18}/> المواقع تقريبية لحماية خصوصية المالكين</div></aside>}</div>
 <div className="trust-line"><ShieldCheck size={20}/><span>الموقع الدقيق يظهر لأطراف الحجز بعد موافقة المالك.</span></div></>:<><section className="intro"><div><div className="eyebrow">مساحتك في قريب</div><h1>أغراضك وحجوزاتك</h1><p>تابع طلباتك وتواصل مع الطرف الآخر من مكان واحد.</p></div><button className="secondary" onClick={()=>{refresh();refreshBookings()}}>تحديث</button></section><div className="dashboard-tabs">{(['rentals','incoming','items'] as const).map((t,i)=><button className={dashboardTab===t?'active':''} key={t} onClick={()=>setDashboardTab(t)}>{['حجوزاتي','طلبات على أغراضي','أغراضي'][i]}</button>)}</div>
 {dashboardTab==='items'?<div className="cards own-cards">{items.filter(i=>i.owner_id===user?.id).map(i=><button className="item-card" key={i.id} onClick={()=>choose(i)}><Art item={i}/><div className="card-body"><h3>{i.title}</h3><p>{i.daily_price} ر.س / يوم</p></div></button>)}{!items.some(i=>i.owner_id===user?.id)&&<div className="empty">لم تضف أي أغراض بعد. ابدأ من «أضف غرضك».</div>}</div>:<div className="booking-list">{bookings.filter(b=>dashboardTab==='rentals'?b.renter_id===user?.id:b.owner_id===user?.id).map(b=><article className="booking panel" key={b.id}><div><span className={'status '+b.status}>{statuses[b.status]}</span><h3>{itemTitle(b)}</h3><p>{itemOf(b)?.daily_price} ر.س / يوم</p>{itemOf(b)?.contact_phone&&<p><a href={`tel:${itemOf(b)!.contact_phone}`}><Phone size={16}/> {itemOf(b)!.contact_phone}</a></p>}</div><div className="booking-actions">{b.status==='pending'&&b.owner_id===user?.id&&<><button disabled={busy} className="primary" onClick={()=>change(b,'accepted')}>قبول</button><button disabled={busy} className="secondary" onClick={()=>change(b,'rejected')}>رفض</button></>}{b.status==='pending'&&b.renter_id===user?.id&&<button disabled={busy} className="secondary" onClick={()=>change(b,'cancelled')}>إلغاء الطلب</button>}{b.status==='accepted'&&b.owner_id===user?.id&&<button disabled={busy} className="primary" onClick={()=>change(b,'completed')}>تأكيد إتمام الاستئجار</button>}<button className="secondary" onClick={()=>setChat(b)}><MessageCircle size={17}/> المحادثة</button><button className="text-button" onClick={()=>{const i=items.find(i=>i.id===b.item_id);if(i)choose(i)}}>تفاصيل الغرض والموقع</button>{b.status==='completed'&&b.renter_id===user?.id&&!reviews.some(r=>r.booking_id===b.id)&&<button className="secondary" onClick={()=>setReviewBooking(b)}>أضف تقييمًا</button>}</div></article>)}{!bookings.some(b=>dashboardTab==='rentals'?b.renter_id===user?.id:b.owner_id===user?.id)&&<div className="empty"><CalendarDays size={40}/><h3>لا توجد حجوزات بعد</h3><p>ستظهر الطلبات وحالاتها هنا.</p></div>}</div>}</>}
 </main><nav className="mobile-bottom-nav" aria-label="التنقل الرئيسي للجوال">
 <button className={view==='explore'&&category==='الكل'?'active':''} onClick={()=>{setView('explore');setCategory('الكل');window.scrollTo({top:0,behavior:'smooth'})}}><House size={21}/><span>الرئيسية</span></button>
 <button className={view==='explore'&&category!=='الكل'?'active':''} onClick={()=>{setView('explore');setCategory('الكل');document.querySelector('.categories')?.scrollIntoView({behavior:'smooth',block:'start'})}}><Compass size={21}/><span>استكشف</span></button>
 <button className="mobile-add" onClick={()=>{if(requireUser()){setAddPoint(null);setModal('add')}}}><span className="mobile-add-icon"><Plus size={25}/></span><span>أضف غرض</span></button>
 <button className={view==='dashboard'?'active':''} onClick={()=>{if(requireUser())setView('dashboard')}}><ClipboardList size={21}/><span>طلباتي</span></button>
 <button onClick={()=>user?setView('dashboard'):setModal('auth')}><UserRound size={21}/><span>حسابي</span></button>
 </nav><footer><a className="brand" href="/">قريب.</a><span>استخدام أكثر، امتلاك أقل.</span><span>نسخة أولية · الدفع والترتيبات عند الاستلام</span></footer>
 {modal==='auth'&&<Modal title="الدخول برقم الجوال" close={()=>setModal(null)}><PhoneLogin onSuccess={()=>{setModal(null);setNotice('تم تسجيل الدخول')}}/></Modal>}
 {modal==='add'&&<Modal notice={notice} title="شارك غرضك مع من حولك" close={()=>{if(!busy)setModal(null)}}><form className="form" onSubmit={e=>{e.preventDefault();if(!requireUser())return;const f=new FormData(e.currentTarget);run(async()=>{const files=(f.getAll('images') as File[]).filter(x=>x.size>0);if(!files.length||files.length>5)throw Error('أضف من صورة إلى خمس صور');const phone=normalizePhone(String(f.get('phone')));const urls:string[]=[];for(const file of files){const blob=await cleanImage(file);const path=`${user!.id}/${crypto.randomUUID()}.webp`;const {error}=await db!.storage.from('item-images').upload(path,blob,{contentType:'image/webp'});if(error)throw Error(error.message);urls.push(db!.storage.from('item-images').getPublicUrl(path).data.publicUrl)}const {error}=await db!.rpc('create_item',{p_title:f.get('title'),p_description:f.get('description'),p_category:f.get('category'),p_price:Number(f.get('price')),p_phone:phone,p_area:f.get('area'),p_lat:Number(f.get('lat')),p_lng:Number(f.get('lng')),p_images:urls});if(error)throw Error(error.message);setModal(null);await refresh();setNotice('تم نشر غرضك بنجاح')})}}><label>اسم الغرض<input name="title" minLength={3} maxLength={100} required placeholder="مثلًا: كاميرا مع عدسة وحقيبة"/></label><label>الوصف<textarea name="description" minLength={10} maxLength={3000} required placeholder="الحالة، الملحقات، وشروط الاستخدام…"/></label><div className="two"><label>الفئة<select name="category">{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>السعر اليومي (ر.س)<input name="price" type="number" min="1" max="100000" step="0.01" required/></label></div><label>رقم التواصل (جوال)<input name="phone" type="tel" dir="ltr" required placeholder="05xxxxxxxx أو +9665xxxxxxxx" maxLength={24}/><small>يظهر للمستأجرين للتواصل المباشر وتنسيق موعد الاستلام.</small></label><label>الصور (1–5، حتى 5 ميجابايت للصورة)<input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple required/></label><label>الحي والمدينة فقط<input name="area" required minLength={2} maxLength={100} placeholder="حي الملقا، الرياض"/></label><button type="button" className="secondary" onClick={()=>locate(true)}><LocateFixed size={18}/> استخدام موقعي للاستلام</button><div className="two"><label>خط العرض<input name="lat" type="number" step="any" min="-90" max="90" required value={addPoint?.lat??''} onChange={e=>setAddPoint({lat:Number(e.target.value),lng:addPoint?.lng??0})}/></label><label>خط الطول<input name="lng" type="number" step="any" min="-180" max="180" required value={addPoint?.lng??''} onChange={e=>setAddPoint({lat:addPoint?.lat??0,lng:Number(e.target.value)})}/></label></div><div className="privacy"><ShieldCheck size={20}/> لا تكتب عنوان المنزل أو الهاتف في الوصف ولا تُظهرهما في الصور. نُخفي الإحداثيات الدقيقة حتى تأكيد الحجز.</div><button className="primary" disabled={busy}>{busy?'جارٍ رفع الصور والنشر…':'نشر الغرض'}</button></form></Modal>}
 {selected&&<Modal notice={notice} title={selected.title} close={closeDetails}><div className="detail"><Art item={selected}/>{selected.images.length>1&&<div className="gallery">{selected.images.slice(1).map(src=><img key={src} src={src} alt="صورة إضافية للغرض"/>)}</div>}<div className="detail-meta"><span>{selected.category} · {selected.area}</span><strong>{selected.daily_price} ر.س / يوم</strong></div><p className="description">{selected.description}</p><div className="privacy"><ShieldCheck size={21}/>{realDistanceKm!=null?<span>المسافة الفعلية بينك وبين المالك: {realDistanceKm} كم — الموقع الدقيق نفسه يبقى خاصًا ولا يُشارك.</span>:'الموقع تقريبي. تظهر لك المسافة الفعلية بعد موافقة المالك على طلب التواصل.'}</div>{selected.owner_id!==user?.id&&<div className="booking-form"><h3>تواصل مع المالك</h3><div className="contact-row"><a className="secondary" href={`tel:${selected.contact_phone}`}><Phone size={18}/> اتصال: {selected.contact_phone}</a><button type="button" disabled={busy} className="primary" onClick={()=>{if(!requireUser())return;run(async()=>{const {error}=await db!.rpc('request_contact',{p_item:selected.id});if(error)throw Error(error.message);await refreshBookings();closeDetails();setView('dashboard');setDashboardTab('rentals');setNotice('أُرسل طلب تواصل إلى المالك. تابع الرد وابدأ المحادثة من حجوزاتك.')})}}><MessageCircle size={18}/> {busy?'جارٍ الإرسال…':'بدء محادثة داخل التطبيق'}</button></div><small>نسّق مباشرة مع المالك موعد الاستلام والمدة والسعر عبر الاتصال أو المحادثة الداخلية.</small></div>}<section className="reviews"><h3>التقييمات {average(selected.id)&&`· ★ ${average(selected.id)}`}</h3>{reviews.filter(r=>r.item_id===selected.id).map(r=><article key={r.id}><span className="stars">{'★'.repeat(r.rating)}</span><p>{r.body}</p></article>)}{!reviews.some(r=>r.item_id===selected.id)&&<p>لم يُقيّم هذا الغرض بعد.</p>}</section></div></Modal>}
 {chat&&<Modal notice={notice} title={`محادثة: ${itemTitle(chat)}`} close={()=>setChat(null)}><div className="chat-messages" aria-live="polite">{messages.map(m=><div className={'bubble '+(m.sender_id===user?.id?'mine':'')} key={m.id}><small>{m.sender_id===user?.id?'أنت':'الطرف الآخر'}</small><p>{m.body}</p><time>{new Date(m.created_at).toLocaleString('ar-SA')}</time></div>)}{!messages.length&&<p>ابدأ المحادثة للتنسيق حول الغرض. لا تشارك عنوانك قبل قبول الحجز.</p>}</div>{['pending','accepted','completed'].includes(chat.status)?<form className="chat-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const body=String(new FormData(form).get('body')).trim();if(!body)return;run(async()=>{const {data,error}=await db!.from('messages').insert({booking_id:chat.id,sender_id:user!.id,body}).select().single();if(error)throw Error(error.message);setMessages(ms=>[...ms,data]);form.reset()})}}><input name="body" aria-label="الرسالة" placeholder="اكتب رسالة…" maxLength={2000} required/><button className="primary" disabled={busy}>إرسال</button></form>:<p>هذه المحادثة للقراءة فقط لأن الحجز ملغي أو مرفوض.</p>}</Modal>}
 {reviewBooking&&<Modal notice={notice} title="كيف كانت تجربتك؟" close={()=>setReviewBooking(null)}><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const {error}=await db!.from('reviews').insert({booking_id:reviewBooking.id,item_id:reviewBooking.item_id,author_id:user!.id,rating:Number(f.get('rating')),body:f.get('body')});if(error)throw Error(error.message);setReviewBooking(null);await refresh();setNotice('شكرًا لمشاركة تقييمك')})}}><label>التقييم<select name="rating">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} من 5</option>)}</select></label><label>تجربتك<textarea name="body" required maxLength={1000}/></label><button disabled={busy} className="primary">نشر التقييم</button></form></Modal>}
 </>;
}

