'use client';
import {useEffect,useState} from 'react';
import {db} from '@/lib/supabase';
import {normalizePhone} from '@/lib/domain.mjs';
export default function PhoneLogin({onSuccess}:{onSuccess:()=>void}){
 const [phone,setPhone]=useState(''),[sentTo,setSentTo]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[cooldown,setCooldown]=useState(0);
 const testLogin=process.env.NEXT_PUBLIC_ENABLE_TEST_LOGIN==='true';
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(c=>Math.max(0,c-1)),1000);return()=>clearTimeout(timer)},[cooldown]);
 async function send(){if(busy||cooldown)return;setBusy(true);setError('');try{if(!db)throw Error('يلزم ربط Supabase وتفعيل رسائل الجوال أولًا.');const number=normalizePhone(phone);const {error}=await db.auth.signInWithOtp({phone:number,options:{channel:'sms',shouldCreateUser:true}});if(error)throw error;setSentTo(number);setCode('');setCooldown(60)}catch(e){setError(e instanceof Error?e.message:'تعذر إرسال الرمز')}finally{setBusy(false)}}
 async function verify(){if(busy)return;setBusy(true);setError('');try{const {error}=await db!.auth.verifyOtp({phone:sentTo,token:code,type:'sms'});if(error)throw error;onSuccess()}catch(e){setError(e instanceof Error?e.message:'تعذر التحقق من الرمز')}finally{setBusy(false)}}
 async function anonymous(){if(busy)return;setBusy(true);setError('');try{if(!db)throw Error('يلزم ربط Supabase أولًا.');const {error}=await db.auth.signInAnonymously();if(error)throw error;onSuccess()}catch(e){setError(e instanceof Error?e.message:'تعذر الدخول التجريبي')}finally{setBusy(false)}}
 return <form className="form" onSubmit={e=>{e.preventDefault();if(sentTo)void verify();else void send()}}><p>سجّل أو أنشئ حسابك برقم الجوال، دون كلمة مرور.</p>{error&&<p className="dialog-notice" role="alert">{error}</p>}{!sentTo?<label>رقم الجوال<input type="tel" autoComplete="tel" dir="ltr" placeholder="05xxxxxxxx أو +9665xxxxxxxx" value={phone} onChange={e=>setPhone(e.target.value)} required maxLength={24}/><small>للأرقام خارج السعودية، اكتب الرقم مع رمز الدولة.</small></label>:<><p>أرسلنا رمز تحقق إلى <bdi>{sentTo}</bdi></p><label>رمز التحقق<input inputMode="numeric" autoComplete="one-time-code" dir="ltr" pattern="[0-9]{6}" minLength={6} maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/[^0-9]/g,''))}/></label></>}<button className="primary" disabled={busy||(!sentTo&&cooldown>0)}>{busy?'جارٍ التنفيذ…':sentTo?'تحقق وتابع':cooldown?`أعد المحاولة خلال ${cooldown} ثانية`:'إرسال رمز التحقق'}</button>{sentTo&&<><button type="button" className="secondary" disabled={busy||cooldown>0} onClick={()=>void send()}>{cooldown?`إعادة الإرسال خلال ${cooldown} ثانية`:'إعادة إرسال الرمز'}</button><button type="button" className="text-button" disabled={busy} onClick={()=>{setSentTo('');setCode('');setError('')}}>تغيير رقم الجوال</button></>}{testLogin&&!sentTo&&<><div className="test-divider"><span>أو للاختبار</span></div><button type="button" className="secondary test-login" disabled={busy} onClick={()=>void anonymous()}>دخول تجريبي سريع</button><small>ينشئ حسابًا مجهولًا داخل Supabase للاختبار فقط. افتح نافذة خاصة ثانية لتجربة الحجز بين مستخدمين.</small></>}</form>
}
