export const countryCodes:{code:string;name:string}[]=[
{code:'+966',name:'السعودية'},
{code:'+971',name:'الإمارات'},
{code:'+965',name:'الكويت'},
{code:'+973',name:'البحرين'},
{code:'+974',name:'قطر'},
{code:'+968',name:'عُمان'},
{code:'+20',name:'مصر'},
{code:'+962',name:'الأردن'},
{code:'+961',name:'لبنان'},
{code:'+963',name:'سوريا'},
{code:'+964',name:'العراق'},
{code:'+967',name:'اليمن'},
{code:'+970',name:'فلسطين'},
{code:'+218',name:'ليبيا'},
{code:'+216',name:'تونس'},
{code:'+213',name:'الجزائر'},
{code:'+212',name:'المغرب'},
{code:'+249',name:'السودان'},
{code:'+222',name:'موريتانيا'},
{code:'+252',name:'الصومال'},
{code:'+253',name:'جيبوتي'},
{code:'+269',name:'جزر القمر'}
];
