import type {Item} from './types';
export const demo:Item[]=[
{id:'demo-1',owner_id:'demo',title:'كاميرا احترافية لذكريات تستحق',description:'كاميرا مع عدسة وحقيبة حمل. مناسبة لتصوير المناسبات والمشاريع الصغيرة. يرجى إعادة المعدات بالحالة نفسها.',category:'تصوير',daily_price:120,contact_phone:'+966501234567',area:'حي الملقا، الرياض',lat:24.80,lng:46.62,images:[]},
{id:'demo-2',owner_id:'demo',title:'خيمة رحلات تتسع لأربعة أشخاص',description:'خيمة سهلة التركيب مع حقيبة وأوتاد. مناسبة لرحلات نهاية الأسبوع.',category:'رحلات',daily_price:65,contact_phone:'+966502345678',area:'حي حطين، الرياض',lat:24.77,lng:46.62,images:[]},
{id:'demo-3',owner_id:'demo',title:'مثقاب لاسلكي مع طقم ملحقات',description:'مثقاب عملي مع بطاريتين وشاحن وطقم رؤوس للاستخدام المنزلي.',category:'أدوات ومعدات',daily_price:35,contact_phone:'+966503456789',area:'حي العقيق، الرياض',lat:24.78,lng:46.64,images:[]},
{id:'demo-4',owner_id:'demo',title:'دراجة جبلية ليوم مليء بالحركة',description:'دراجة للبالغين مع خوذة وقفل. يرجى فحص المقاس عند الاستلام.',category:'رياضة',daily_price:55,contact_phone:'+966504567890',area:'حي النخيل، الرياض',lat:24.75,lng:46.63,images:[]},
{id:'demo-5',owner_id:'demo',title:'سماعات DJ احترافية',description:'نظام صوت مناسب للحفلات والمناسبات، يشمل سماعتين ومكسر أساسي.',category:'تجهيز الحفلات',daily_price:180,contact_phone:'+966505678901',area:'حي حطين، الرياض',lat:24.77,lng:46.60,images:[]},
{id:'demo-6',owner_id:'demo',title:'كوشة أفراح أنيقة',description:'كوشة مناسبات بتصميم عصري قابلة للتخصيص حسب المناسبة.',category:'تجهيز الحفلات',daily_price:650,contact_phone:'+966506789012',area:'حي قرطبة، الرياض',lat:24.82,lng:46.72,images:[]},
{id:'demo-7',owner_id:'demo',title:'طاولات ضيافة للمناسبات',description:'مجموعة طاولات ضيافة مناسبة للأفراح والاستقبالات والمناسبات الخاصة.',category:'تجهيز الحفلات',daily_price:120,contact_phone:'+966507890123',area:'حي المونسية، الرياض',lat:24.83,lng:46.78,images:[]},
{id:'demo-8',owner_id:'demo',title:'خلاط عجين كهربائي بسعة كبيرة',description:'خلاط عجين احترافي مناسب للمناسبات والخبز بكميات كبيرة، مع ملحقات الخفق والعجن.',category:'أدوات مطبخ',daily_price:45,contact_phone:'+966508901234',area:'حي الياسمين، الرياض',lat:24.85,lng:46.65,images:[]}
];
